apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sykdom-i-familien-sanity
  namespace: default
  labels:
    team: '{{team}}'
spec:
  image: '{{ image }}:{{ tag }}'
  port: 8080
  liveness:
    path: '{{BASE_URL}}/internal/isAlive'
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: '{{baseurl}}/internal/isReady'
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: '2'
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 768Mi
  ingresses:
    - https://sykdom-i-familien-sanity.nais.oera-q.local
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  webproxy: true
  env:
    - name: BASE_URL
      value: '/familie/sykdom-i-familien-sanity'