# This workflow trigger on push to any branch.
name: CI / CD
on:
  push:
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENCE'
      - 'CODEOWNERS'
    branches:

jobs:
  test:
      name: Test Code
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [8.x, 10.x, 12.x]

      steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and test
        run: |
          npm ci
#          npm run test
        env:
          CI: true

  build-code-and-deploy-studio:
    name: Build code and push docker image
    if: github.ref == 'refs/heads/dev-*' || github.ref == 'refs/heads/master' # Build and push docker if branch is either master or dev-*
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: build code
        run: |
          npm i @sanity/cli
          npm ci
          npm run build
          ls -la          
      - name: upload dist folder to next job.
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist/
      - name: pass tag file to next job.
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist/

  deploy-dev-sbs:
    name: Deploy to dev-sbs
    if: github.ref == 'refs/heads/dev-*' || github.ref == 'refs/heads/master' # Deploy if branch is either master or dev-*
    needs: build-code-and-deploy-studio # Depends on build-code-and-deploy-studio job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        # Download the image and tag file to use for the deployment cli.
      - name: Download dist folder
        uses: actions/download-artifact@v1
        with:
          name: dist
      - name: unpack
        run: |
          cp dist/ .
      - name: debug
        run: ls -la
      - name: deploy to studio
        run: npm run deploy
        env:
          SANITY_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}

  deploy-prod-sbs:
    name: Deploy to prod-sbs
    if: github.ref == 'refs/heads/master'  # If the branch is master
    needs: build-code-and-deploy-studio # Depends on build-code-and-deploy-studio job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        # Download the image and tag file to use for the deployment cli.
      - name: Download image file
        uses: actions/download-artifact@v1
        with:
          name: docker_image
      - name: Download tag file
        uses: actions/download-artifact@v1
        with:
          name: docker_tag
      - name: unpack
        run: |
          cp docker_image/.docker_image .
          cp docker_tag/.docker_tag .
      - name: debug
        run: ls -la
      - name: deploy to prod-sbs
        uses: navikt/deployment-cli/action@0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          cluster: prod-sbs
          team: dusseldorf
          resources: nais/prod-sbs.yml