# This workflow trigger on push to any branch.
name: CI / CD
on:
  push:
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENCE'
      - 'CODEOWNERS'
    branches:

jobs:
  test:
      name: Test Code
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [8.x, 10.x, 12.x]

      steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and test
        run: |
          npm ci
#          npm run test
        env:
          CI: true

  build-code-and-deploy-studio:
    name: Build code and push docker image
    if: github.ref == 'refs/heads/dev-*' || github.ref == 'refs/heads/master' # Build and push docker if branch is either master or dev-*
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: build code
        run: |
          npm i @sanity/cli
          npm ci
          npm run deploy
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}          
      - name: upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist/